<?php
declare(strict_types=1);

/**
 * Temporary, uniquely owned HOME PC data for read-only filled-page browser QA.
 * Run --prepare, the browser harness, then --cleanup sequentially. No DDL/mail.
 * Credentials and private receipt/status URLs are written only to ignored tmp.
 */
define('RENTALS_DIAGNOSTIC_READ_ONLY', true); // Suppress diagnostic logs/key creation.

function browserFixtureWrite(string $path, string $bytes, bool $create = false): void
{
    $stream = @fopen($path, $create ? 'xb' : 'c+b');
    if ($stream === false) { throw new RuntimeException('Private fixture file unavailable.'); }
    try {
        if (!flock($stream, LOCK_EX) || !ftruncate($stream, 0)
            || fwrite($stream, $bytes) !== strlen($bytes) || !fflush($stream)) {
            throw new RuntimeException('Private fixture file write failed.');
        }
    } catch (Throwable $error) {
        fclose($stream);
        if ($create) { @unlink($path); } // Only the file opened exclusively by this call.
        throw $error;
    }
    fclose($stream);
    @chmod($path, 0600);
}

function browserFixtureSave(string $path, array $state, bool $create = false): void
{
    browserFixtureWrite($path, json_encode($state, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . "\n", $create);
}

function browserFixtureCounts(App\Core\Database $db): array
{
    $tables = [...array_keys(App\Services\RentalSchema::COLUMNS), 'landing_page_visits', 'tracking_events', 'inquiries'];
    $counts = [];
    foreach ($tables as $table) {
        $counts[$table] = (int) $db->selectValue('SELECT COUNT(*) FROM ' . $db->identifier($table, $tables));
    }
    return $counts;
}

function browserFixturePlain(array $state): string
{
    return base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lXcAAAAASUVORK5CYII=', true)
        . "\n3AM-BROWSER-QA:" . $state['key'];
}

/** Test-only encryption of generated bytes; production upload provenance stays intact. */
function browserFixtureProof(array &$state, string $statePath): string
{
    if (!is_file(BASE_PATH . '/storage/rentals/payment-key.php')) {
        throw new RuntimeException('Existing local proof key is required.');
    }
    $reflection = new ReflectionClass(App\Services\RentalPaymentProof::class);
    $key = $reflection->getMethod('key')->invoke(null); // Secret remains in memory.
    $magic = $reflection->getConstant('MAGIC');
    if (!is_string($key) || strlen($key) !== 32 || $magic !== '3AMPROOF1') {
        throw new RuntimeException('Unsupported proof fixture format.');
    }
    $nonce = random_bytes(12);
    $tag = '';
    $cipher = openssl_encrypt(browserFixturePlain($state), 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $nonce, $tag);
    unset($key);
    if ($cipher === false || strlen($tag) !== 16) { throw new RuntimeException('Fixture proof encryption failed.'); }
    $reference = 'micro/payment/' . bin2hex(random_bytes(16)) . '.png';
    // Persist ownership before creating bytes so interrupted preparation is recoverable.
    $state['proof_references'][] = $reference;
    browserFixtureSave($statePath, $state);
    $path = App\Services\RentalStorage::root() . '/payment/' . basename($reference);
    browserFixtureWrite($path, $magic . $nonce . $tag . $cipher, true);
    if (App\Services\RentalPaymentProof::response($reference)->body() !== browserFixturePlain($state)) {
        throw new RuntimeException('Fixture proof did not round-trip through the application reader.');
    }
    return $reference;
}

function browserFixtureImage(array &$state, string $statePath, string $source): string
{
    $bytes = @file_get_contents(BASE_PATH . '/' . $source);
    if ($bytes === false || @getimagesize(BASE_PATH . '/' . $source) === false) {
        throw new RuntimeException('Repository fixture image unavailable.');
    }
    $reference = 'micro/rentals/products/' . bin2hex(random_bytes(16)) . '.jpg';
    $state['image_references'][] = $reference;
    browserFixtureSave($statePath, $state);
    $path = App\Services\RentalStorage::root() . '/rentals/products/' . basename($reference);
    browserFixtureWrite($path, $bytes . "\n3AM-BROWSER-QA:" . $state['key'], true);
    if (@getimagesize($path) === false) { throw new RuntimeException('Generated fixture image is unreadable.'); }
    return $reference;
}

/** Validate every parent before any delete; child deletes use only owned IDs. */
function browserFixtureCleanup(App\Core\Database $db, array &$state, string $statePath, string $accountsPath): array
{
    if (($state['version'] ?? null) !== 1 || preg_match('/^[a-f0-9]{16}$/D', (string) ($state['key'] ?? '')) !== 1
        || !is_array($state['ids'] ?? null) || !is_array($state['baseline_counts'] ?? null)) {
        throw new RuntimeException('Unrecognized private fixture ownership state.');
    }
    $ids = $state['ids'];
    foreach ($ids as $id) {
        if (!is_int($id) || $id < 1) { throw new RuntimeException('Invalid fixture ownership ID.'); }
    }
    $slug = 'browser-' . $state['key'];
    $name = '[TEST] Browser ' . $state['key'];
    $checks = [
        'admin' => ['users', 'email', $slug . '-admin@example.test'],
        'customer' => ['users', 'email', $slug . '-customer@example.test'],
        'equipment_category' => ['rental_categories', 'slug', $slug . '-equipment'],
        'service_category' => ['rental_categories', 'slug', $slug . '-services'],
        'equipment' => ['rental_items', 'slug', $slug . '-camera'],
        'service' => ['rental_items', 'slug', $slug . '-production'],
        'payment_method' => ['payment_methods', 'name', $name . ' Manual payment'],
        'equipment_order' => ['order_header', 'order_number', 'BROWSER-' . strtoupper($state['key'])],
        'service_payment_form' => ['rental_service_requests', 'reference', 'BROWSER-' . strtoupper($state['key']) . '-A'],
        'service_admin_payment_review' => ['rental_service_requests', 'reference', 'BROWSER-' . strtoupper($state['key']) . '-B'],
    ];
    foreach ($checks as $key => [$table, $field, $expected]) {
        if (!isset($ids[$key])) { continue; }
        // Table/field names originate only in the fixed mapping above.
        $row = $db->selectOne('SELECT `' . $field . '` FROM `' . $table . '` WHERE id=?', [$ids[$key]]);
        if ($row !== null && $row[$field] !== $expected) { throw new RuntimeException('Fixture ownership mismatch; no cleanup performed.'); }
    }
    foreach (['equipment_order' => 'order_header', 'service_payment_form' => 'rental_service_requests',
        'service_admin_payment_review' => 'rental_service_requests', 'cart' => 'carts'] as $key => $table) {
        if (!isset($ids[$key])) { continue; }
        $row = $db->selectOne('SELECT user_id FROM `' . $table . '` WHERE id=?', [$ids[$key]]);
        if ($row !== null && (int) $row['user_id'] !== ($ids['customer'] ?? 0)) {
            throw new RuntimeException('Fixture child ownership mismatch; no cleanup performed.');
        }
    }
    foreach (['equipment' => 'equipment_category', 'service' => 'service_category'] as $key => $category) {
        if (!isset($ids[$key])) { continue; }
        $row = $db->selectOne('SELECT category_id FROM rental_items WHERE id=?', [$ids[$key]]);
        if ($row !== null && (int) $row['category_id'] !== ($ids[$category] ?? 0)) {
            throw new RuntimeException('Fixture item ownership mismatch; no cleanup performed.');
        }
    }
    // A tampered/nonfixture reference is never removed, even when present in JSON.
    $marker = "\n3AM-BROWSER-QA:" . $state['key'];
    foreach ($state['proof_references'] ?? [] as $reference) {
        $path = App\Services\RentalPaymentProof::path($reference);
        if ($path !== null && App\Services\RentalPaymentProof::response($reference)->body() !== browserFixturePlain($state)) {
            throw new RuntimeException('Proof fixture ownership mismatch; no cleanup performed.');
        }
    }
    foreach ($state['image_references'] ?? [] as $reference) {
        if (!is_string($reference) || preg_match('#^micro/rentals/products/[a-f0-9]{32}\.jpg$#D', $reference) !== 1) {
            throw new RuntimeException('Image fixture path mismatch; no cleanup performed.');
        }
        $path = App\Services\RentalStorage::path($reference);
        if ($path !== null && !str_ends_with((string) @file_get_contents($path), $marker)) {
            throw new RuntimeException('Image fixture ownership mismatch; no cleanup performed.');
        }
    }
    $db->transaction(static function (App\Core\Database $db) use ($ids, $checks): void {
        if (isset($ids['equipment_order'])) {
            $db->delete('DELETE FROM rental_notification_deliveries WHERE order_id=?', [$ids['equipment_order']]);
            $db->delete('DELETE FROM order_details WHERE order_header_id=?', [$ids['equipment_order']]);
        }
        foreach (['service_payment_form', 'service_admin_payment_review'] as $key) {
            if (isset($ids[$key])) { $db->delete('DELETE FROM rental_notification_deliveries WHERE service_request_id=?', [$ids[$key]]); }
        }
        if (isset($ids['cart'])) {
            $db->delete('DELETE FROM cart_items WHERE cart_id=?', [$ids['cart']]);
            $db->delete('DELETE FROM carts WHERE id=? AND user_id=?', [$ids['cart'], $ids['customer']]);
        }
        foreach (['equipment_order', 'service_payment_form', 'service_admin_payment_review', 'equipment', 'service',
            'equipment_category', 'service_category', 'payment_method', 'customer', 'admin'] as $key) {
            if (!isset($ids[$key])) { continue; }
            [$table, $field, $expected] = $checks[$key];
            if ($table === 'users') { $db->delete('DELETE FROM rental_password_resets WHERE user_id=?', [$ids[$key]]); }
            $db->delete('DELETE FROM `' . $table . '` WHERE id=? AND `' . $field . '`=?', [$ids[$key], $expected]);
        }
    });
    foreach ($state['proof_references'] ?? [] as $reference) {
        App\Services\RentalPaymentProof::remove($reference);
        if (App\Services\RentalPaymentProof::path($reference) !== null) { throw new RuntimeException('Owned proof cleanup incomplete.'); }
    }
    foreach ($state['image_references'] ?? [] as $reference) {
        App\Services\RentalManagedImage::remove($reference, 'product');
        if (App\Services\RentalStorage::path($reference) !== null) { throw new RuntimeException('Owned image cleanup incomplete.'); }
    }
    foreach ($checks as $key => [$table, $field, $expected]) {
        if (isset($ids[$key]) && $db->selectValue('SELECT id FROM `' . $table . '` WHERE id=? AND `' . $field . '`=?', [$ids[$key], $expected]) !== null) {
            throw new RuntimeException('Owned row cleanup incomplete.');
        }
    }
    $deltas = [];
    foreach (browserFixtureCounts($db) as $table => $count) {
        if ($count !== ($state['baseline_counts'][$table] ?? null)) { $deltas[$table] = $count - ($state['baseline_counts'][$table] ?? 0); }
    }
    // Never restore other records/counts: independent local activity is preserved.
    if (is_file($accountsPath) && !@unlink($accountsPath)) { throw new RuntimeException('Private fixture credential cleanup incomplete.'); }
    if (is_file($statePath) && !@unlink($statePath)) { throw new RuntimeException('Private fixture state cleanup incomplete.'); }
    return $deltas;
}

function browserFixtureMain(array $argv): void
{
    if (PHP_SAPI !== 'cli' || count($argv) !== 2 || !in_array($argv[1], ['--prepare', '--cleanup'], true)) {
        throw new RuntimeException('Use exactly --prepare or --cleanup from CLI.');
    }
    // CLI SCRIPT_NAME lives under /tests; generated browser routes must use
    // the authorized XAMPP front-controller mount rather than that CLI path.
    $_SERVER['SCRIPT_NAME'] = '/3am-web/index.php';
    $container = require dirname(__DIR__) . '/bootstrap.php';
    ini_set('display_errors', '0');
    $connection = config('database.connections.mysql');
    if (config('app.env') !== 'local' || ($connection['host'] ?? '') !== '127.0.0.1'
        || (int) ($connection['port'] ?? 0) !== 3306 || ($connection['database'] ?? '') !== 'd3am_rentals_new'
        || config('mail.enabled') !== false) {
        throw new RuntimeException('STOP: Exact HOME PC database and disabled email are required before connecting.');
    }
    $db = $container->get(App\Core\Database::class);
    $identity = $db->selectOne('SELECT DATABASE() AS db, @@port AS port');
    if (($identity['db'] ?? '') !== 'd3am_rentals_new' || (int) ($identity['port'] ?? 0) !== 3306) {
        throw new RuntimeException('STOP: Connected local database identity mismatch.');
    }
    if ((int) $db->selectValue('SELECT GET_LOCK(?,0)', ['3am-home-browser-fixtures']) !== 1) {
        throw new RuntimeException('STOP: Another browser fixture command is active.');
    }
    $statePath = BASE_PATH . '/storage/tmp/browser-fixture-state.json';
    $accountsPath = BASE_PATH . '/storage/tmp/browser-fixture-accounts.txt';
    $state = null;
    $prepared = false;
    try {
        if ($argv[1] === '--cleanup') {
            if (!is_file($statePath)) {
                if (is_file($accountsPath)) { throw new RuntimeException('Credential file has no ownership state; investigate locally before cleanup.'); }
                echo "No browser fixtures retained.\n";
                return;
            }
            $state = json_decode((string) file_get_contents($statePath), true, 512, JSON_THROW_ON_ERROR);
            $deltas = browserFixtureCleanup($db, $state, $statePath, $accountsPath);
            echo "Cleanup: all owned browser rows, images, proofs and private account/state files removed.\n";
            echo $deltas === [] ? "Baseline row counts restored; no browser fixtures retained.\n"
                : 'Independent local row-count differences preserved: ' . json_encode($deltas) . ".\n";
            return;
        }
        if (is_file($statePath) || is_file($accountsPath)) {
            throw new RuntimeException('STOP: Existing browser fixture files must be cleaned first.');
        }
        if ((new App\Services\RentalSchema($db))->inspect()['issues'] !== []) {
            throw new RuntimeException('STOP: Local schema diagnostic must pass before browser fixtures.');
        }
        // Use only established protected local directories; no storage/key config changes.
        foreach (['payment', 'rentals/products'] as $directory) {
            $path = App\Services\RentalStorage::root() . '/' . $directory;
            if (!is_dir($path) || !is_writable($path) || !is_file($path . '/.htaccess')) {
                throw new RuntimeException('STOP: Existing protected local proof/product directories are required.');
            }
        }
        $state = ['version' => 1, 'key' => bin2hex(random_bytes(8)), 'created_at' => date(DATE_ATOM), 'ready' => false,
            'baseline_counts' => browserFixtureCounts($db), 'ids' => [], 'proof_references' => [], 'image_references' => [], 'routes' => []];
        browserFixtureSave($statePath, $state, true);
        $slug = 'browser-' . $state['key'];
        $name = '[TEST] Browser ' . $state['key'];
        $equipmentImage = browserFixtureImage($state, $statePath, 'media/rentals-camera-lineup.jpg');
        $galleryImage = browserFixtureImage($state, $statePath, 'media/rentals-led-panels.jpg');
        $equipmentProof = browserFixtureProof($state, $statePath);
        $serviceProof = browserFixtureProof($state, $statePath);
        $state['proof_available'] = true;
        $accounts = [];
        $db->beginTransaction();
        try {
            // Persist each owned ID during the transaction for safe crash recovery.
            $insert = static function (string $key, string $sql, array $bindings) use ($db, &$state, $statePath): int {
                $id = $db->insert($sql, $bindings);
                $state['ids'][$key] = $id;
                browserFixtureSave($statePath, $state);
                return $id;
            };
            foreach (['admin', 'customer'] as $role) {
                $password = bin2hex(random_bytes(18));
                $email = $slug . '-' . $role . '@example.test';
                $insert($role, 'INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)',
                    [$name . ' ' . ucfirst($role), $email, password_hash($password, PASSWORD_DEFAULT), $role]);
                $accounts[$role] = ['email' => $email, 'password' => $password];
            }
            $equipmentCategory = $insert('equipment_category',
                'INSERT INTO rental_categories(name,slug,description,image_path,is_active,is_service) VALUES(?,?,?,?,1,0)',
                [$name . ' Equipment', $slug . '-equipment', 'Fictional browser QA equipment category.', $equipmentImage]);
            $serviceCategory = $insert('service_category',
                'INSERT INTO rental_categories(name,slug,description,image_path,is_active,is_service) VALUES(?,?,?,?,1,1)',
                [$name . ' Services', $slug . '-services', 'Fictional browser QA service category.', $galleryImage]);
            $equipment = $insert('equipment',
                "INSERT INTO rental_items(category_id,name,slug,sku,description,ideal_use,image_path,additional_image_paths,is_active,availability_status,rental_unit,rental_rate,security_deposit,available_quantity) VALUES(?,?,?,?,?,?,?,?,1,'available','day',100,25,5)",
                [$equipmentCategory, $name . ' Camera', $slug . '-camera', strtoupper($slug) . '-CAM',
                    'Fictional equipment for filled-page local browser testing.', 'Local browser layout and gallery checks.',
                    $equipmentImage, json_encode([$galleryImage], JSON_THROW_ON_ERROR)]);
            $service = $insert('service',
                "INSERT INTO rental_items(category_id,name,slug,sku,description,ideal_use,image_path,is_active,availability_status,rental_unit,rental_rate,security_deposit,available_quantity) VALUES(?,?,?,?,?,?,?,1,'inquire','event',0,0,0)",
                [$serviceCategory, $name . ' Production crew', $slug . '-production', strtoupper($slug) . '-SRV',
                    'Fictional local service; no real booking or personnel.', 'Local quote and payment review layouts.', $galleryImage]);
            $method = $insert('payment_method',
                "INSERT INTO payment_methods(name,type,provider,account_name,account_number,is_active) VALUES(?,'manual','Local QA','Fictional browser account','0000000000',1)",
                [$name . ' Manual payment']);
            $cart = $insert('cart', 'INSERT INTO carts(user_id) VALUES(?)', [$state['ids']['customer']]);
            $cartDate = (new DateTimeImmutable('today'))->modify('+10 days')->format('Y-m-d');
            $insert('cart_item', 'INSERT INTO cart_items(cart_id,rental_item_id,quantity,rental_start_date,rental_end_date) VALUES(?,?,1,?,?)',
                [$cart, $equipment, $cartDate, $cartDate]);
            $orderDate = (new DateTimeImmutable('today'))->modify('+20 days')->format('Y-m-d');
            $statusToken = bin2hex(random_bytes(32));
            $order = $insert('equipment_order',
                'INSERT INTO order_header(order_number,user_id,customer_name,customer_email,customer_phone,payment_method_id,payment_reference,subtotal,security_deposit,total_amount,notes,payment_proof_path,status_token,payment_status) VALUES(?,?,?,?,?,?,?,100,25,125,?,?,?,0)',
                ['BROWSER-' . strtoupper($state['key']), $state['ids']['customer'], $name . ' Customer', $accounts['customer']['email'],
                    '0000000000', $method, 'FICTIONAL-BROWSER-PAYMENT', 'Fictional local browser fixture.', $equipmentProof, $statusToken]);
            $insert('equipment_order_detail',
                'INSERT INTO order_details(order_header_id,rental_item_id,item_name,quantity,rental_start_date,rental_end_date,unit_rate,line_total) VALUES(?,?,?,1,?,?,100,100)',
                [$order, $equipment, $name . ' Camera', $orderDate, $orderDate]);
            foreach (['service_payment_form' => ['A', 'unpaid', null, null],
                'service_admin_payment_review' => ['B', 'pending', $method, $serviceProof]] as $key => [$suffix, $paymentStatus, $paymentMethod, $proof]) {
                $insert($key,
                    "INSERT INTO rental_service_requests(reference,submission_key,user_id,rental_item_id,service_name,customer_name,customer_email,customer_phone,event_start_date,event_end_date,location,details,status,customer_message,reviewed_by,reviewed_at,notification_attempted_at,quote_amount,quote_notes,quote_version,payment_method_id,payment_reference,payment_proof_path,payment_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'approved',?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1500,?,1,?,?,?,?)",
                    ['BROWSER-' . strtoupper($state['key']) . '-' . $suffix, bin2hex(random_bytes(32)), $state['ids']['customer'],
                        $service, $name . ' Production crew', $name . ' Customer', $accounts['customer']['email'], '0000000000',
                        $orderDate, $orderDate, 'Fictional QA venue', 'Fictional service requirements for local layout review.',
                        'Approved for fictional layout testing only.', $state['ids']['admin'], 'Fictional local quotation, no real payment requested.',
                        $paymentMethod, $paymentStatus === 'pending' ? 'FICTIONAL-SERVICE-PAYMENT' : null, $proof, $paymentStatus]);
            }
            $routes = [
                'equipment_catalogue' => '/rentals/items?type=equipment&category=' . $slug . '-equipment',
                'services_catalogue' => '/rentals/items?type=services&category=' . $slug . '-services',
                'customer_orders' => '/rentals/orders',
                'customer_order_status' => '/rentals/order-status/' . $statusToken,
                'customer_receipt' => '/rentals/confirmation/' . $statusToken,
                'customer_equipment_proof' => '/rentals/orders/' . $order . '/proof',
                'customer_service_payment' => '/rentals/service-requests/' . $state['ids']['service_payment_form'],
                'customer_service_payment_review' => '/rentals/service-requests/' . $state['ids']['service_admin_payment_review'],
                'customer_service_proof' => '/rentals/service-requests/' . $state['ids']['service_admin_payment_review'] . '/proof',
                'customer_service_request_form' => '/rentals/services/' . $service . '/request',
                'admin_equipment_order' => '/rentals/admin/orders/' . $order,
                'admin_equipment_proof' => '/rentals/admin/proof/' . $order,
                'admin_service_review' => '/rentals/admin/service-requests/' . $state['ids']['service_admin_payment_review'],
                'admin_service_proof' => '/rentals/service-requests/' . $state['ids']['service_admin_payment_review'] . '/proof',
                'admin_item_edit' => '/rentals/admin/items/' . $equipment . '/edit',
                'admin_category_edit' => '/rentals/admin/categories/' . $equipmentCategory . '/edit',
                'admin_payment_edit' => '/rentals/admin/payments/' . $method . '/edit',
                'cart' => '/rentals/cart', 'checkout' => '/rentals/checkout',
            ];
            foreach ($routes as $key => $path) { $state['routes'][$key] = url($path); }
            browserFixtureWrite($accountsPath, 'admin: ' . $accounts['admin']['email'] . "\nPassword: " . $accounts['admin']['password']
                . "\n\ncustomer: " . $accounts['customer']['email'] . "\nPassword: " . $accounts['customer']['password'] . "\n", true);
            unset($accounts, $password, $statusToken);
            $state['ready'] = true;
            browserFixtureSave($statePath, $state);
            $db->commit();
            $prepared = true;
            echo "Prepared: 2 fictional accounts, 2 categories/items, 1 manual method, 1 filled Cart, 1 Pending Equipment order, 2 quoted Service requests, 2 encrypted proofs and 2 gallery images.\n";
            echo "Private files: storage/tmp/browser-fixture-accounts.txt and storage/tmp/browser-fixture-state.json.\n";
            echo "Temporary browser fixtures retained until --cleanup; no email, DDL, existing records or environment changes.\n";
        } catch (Throwable $error) {
            if ($db->inTransaction()) { $db->rollBack(); }
            throw $error;
        }
    } finally {
        try {
            if ($argv[1] === '--prepare' && !$prepared && is_array($state)) {
                if ($db->inTransaction()) { $db->rollBack(); }
                browserFixtureCleanup($db, $state, $statePath, $accountsPath);
                echo "Failed preparation cleanup: owned rows/files removed; no browser fixtures retained.\n";
            }
        } finally { $db->selectValue('SELECT RELEASE_LOCK(?)', ['3am-home-browser-fixtures']); }
    }
}

try {
    browserFixtureMain($argv);
} catch (Throwable $error) {
    // Do not emit a trace, bindings, credentials, keys or private routes.
    $safe = $error instanceof RuntimeException && $error->getPrevious() === null ? $error->getMessage() : 'Local fixture operation failed; inspect ownership state privately before retrying.';
    fwrite(STDERR, "STOP: " . $safe . "\n");
    exit(1);
}
